name=robotat-linalg
version=0.2
author=Andrea Pineda <bar20575@uvg.edu.gt>, Daniel Pineda <bar18714@uvg.edu.gt>, Miguel Zea <mezea@uvg.edu.gt>
maintainer=Daniel Pineda <bar18714@uvg.edu.gt>, Miguel Zea <mezea@uvg.edu.gt>
sentence=Robotat Embedded C Libraries
paragraph=Embedded C libraries for numerical computation, convex optimization, control and robotics algorithms, developed at Universidad del Valle de Guatemala.
url=https://github.com/andreabp19/robotat-linalg
includes=matf32.h, linsolve.h, quadprog.h, robotat_control.h, robotat_robotics.h